?start : statement

statement: querykeyword querytype wherekeyword wherefullcondition+ 
    | querykeyword querytype

querytype: data
 
data: "BGC" | "bgc" | "Bgc"

wherekeyword: "WHERE" | "where" | "Where"
querykeyword: "QUERY" | "query" | "Query"

wherefullcondition: wherefullcondition booleanandconjunction wherefullcondition
    | condition


condition : condition_feild equal value
    | gene_condition equal gene 

condition_feild : "test1"
    | "test2"
gene_condition : "gene_condition"


value : NUMBER
    |gene

gene : /[ACGTU]+/
equal : "="

booleanandconjunction : "and" | "AND"
boolean: "and"
    | "or"
    | "not"

%import common.CNAME -> NAME
%import common.NUMBER -> NUMBER
%import common.WS_INLINE

%ignore WS_INLINE

