?start : statement

statement: querykeyword querytype wherekeyword wherefullcondition+ 
    | querykeyword querytype

querytype: data
 
data: "BGC" | "bgc" | "Bgc"

wherekeyword: "WHERE" | "where" | "Where"
querykeyword: "QUERY" | "query" | "Query"

wherefullcondition: wherefullcondition booleanandconjunction wherefullcondition
    | condition


condition : condition_feild equal value
    // | gene_condition equal gene 
    // | domain_condition equal domain_value
    | taxonomy_condition equal taxonomy_value [":" cardinality]
    | enzyme_condition equal enzyme_value

condition_feild : "test1" -> test1
    | "test2" -> test2
    | "BGC type" -> bgc_type
    | "compound" -> compound
taxonomy_condition : species
    | genus
    | family
    | order
    | class
    | phylum
    | kingdom
    | superkingdom
    species : "species"
    genus : "genus"
    family : "family"
    order : "order"
    class : "class"
    phylum : "phylum"
    kingdom : "kingdom"
    superkingdom : "domain" | "DOMAIN" | "superkingdom" 
enzyme_condition: "ENZYME" | "enzyme"


value : NUMBER 
    | NAME
    |gene
taxonomy_value: NAME
    |"(" taxonomy_value ( booleanandconjunction taxonomy_value)+ ")"
cardinality : "cardinality" equal range

domain_value: "dv1" 
    | "dv2"
    | "(" domain_value (booleanorconjunction domain_value)+ ")"
    | domain_value (":" domain_value )+
enzyme_value : gene
    | sequencematch
    | gene ":" evalue ":" mismatch
    evalue : "evalue" [greaterthan|lessthan] NUMBER
    mismatch : "mismatch" equal NUMBER
    sequencematch : "sequencematch" "(" gene "," evalue "," mismatch ")"

range : "range" "(" NUMBER "," NUMBER ")"
gene : /[ACGTU]+/
equal : "="
greaterthan : ">"
lessthan : "<"

booleanandconjunction : "and" | "AND" | "And"
booleanorconjunction : "or" | "OR" | "Or"

%import common.CNAME -> NAME
%import common.ESCAPED_STRING   -> STRING
%import common.SIGNED_NUMBER    -> NUMBER
%import common.WS
%ignore WS